### ISSUE TITLE
"this.stylesheet is null"

### ISSUE THREAD

**Issue by mattfordham** [jimjeffers/Sauce#1]
Hi there,

I am attempting to use Sauce, but Firebug is giving me this error:

`this.stylesheet is null
this.index = this.stylesheet.cssRules.length;`

Any idea what I am doing wrong? Thanks!

**Comment by jimjeffers** [comment]
Thanks Matt! I ran into this issue too. I need to push a fix when I get back to hacking on Sauce again. This is a good kick in the pants to do so. :) I'll look into pushing my fix from earlier (still rough around the edges) in the next day or so.

**Comment by mattfordham** [comment]
Thanks! That'd be excellent!

**Comment by jimjeffers** [comment]
Hey I just checked my uncommitted changes and it looked safe to push. Give the latest a try and see if it works out for ya!

**Comment by mattfordham** [comment]
That did it, thanks!
